<?php
	/* Generated by Wixnit Class Builder 
	// Feb, 29/2020
	// Building class for Bakerysaleitem
	*/

	class Bakerysaleitem
	{
		public $Id = "";
		public $Created = 0;
		public $Item = "";
		public $Quantity = 0;

        private $subscriber = null;

        function __construct(Subscriber $subscriber)
        {
            $this->subscriber = $subscriber;
        }

        public function Initialize($arg=null)
		{
			if($arg != null)
			{
				$db = $this->subscriber->GetDB();

				$res = $db->query("SELECT * FROM bakerysaleitem WHERE bakerysaleitemid='$arg'");

				if($res->num_rows > 0)
				{
					$row = $res->fetch_assoc();
				
					$this->Id = $row['bakerysaleitemid'];
					$this->Created = new WixDate($row['created']);
					$this->Item = new Pastry($this->subscriber);
					$this->Item->Initialize($row['item']);
					$this->Quantity = Convert::ToInt($row['quantity']);
				}
			}
		}

		public function Save()
		{
			$db = $this->subscriber->GetDB();

			$id = $this->Id;
			$created = time();
			$item = addslashes(is_a($this->Item, "Pastry") ? $this->Item->Id : $this->Item);
			$quantity = Convert::ToInt($this->Quantity);

			if($res = $db->query("SELECT bakerysaleitemid FROM bakerysaleitem WHERE bakerysaleitemid='$id'")->num_rows > 0)
			{
				$db->query("UPDATE bakerysaleitem SET item='$item',quantity='$quantity' WHERE bakerysaleitemid = '$id'");
			}
			else
			{
				redo: ;
				$id = Random::GenerateId(16);
				if($db->query("SELECT bakerysaleitemid FROM bakerysaleitem WHERE bakerysaleitemid='$id'")->num_rows > 0)
				{
					goto redo;
				}
				$this->Id = $id;
				$db->query("INSERT INTO bakerysaleitem(bakerysaleitemid,created,item,quantity) VALUES ('$id','$created','$item','$quantity')");
			}
		}

		public function Delete()
		{
			$db = $this->subscriber->GetDB();

			$id = $this->Id;
			$db->query("DELETE FROM bakerysaleitem WHERE bakerysaleitemid='$id'");

			//Deleting Associated Objects
			/*n			$this->Item->Delete();
			*/
		}

		public static function Search(Subscriber $subscriber, $term='')
		{
			$db = $subscriber->GetDB();
			$ret = array();
			$i = 0;

			$res = $db->query("SELECT * FROM bakerysaleitem WHERE item LIKE '%$term%' OR quantity LIKE '%$term%'");
			while(($row = $res->fetch_assoc()) != null)
			{
                $ret[$i] = new Bakerysaleitem($subscriber);
                $ret[$i]->Id = $row['bakerysaleitemid'];
                $ret[$i]->Created = new WixDate($row['created']);
                $ret[$i]->Item = $row['item'];
                $ret[$i]->Quantity = Convert::ToInt($row['quantity']);
				$i++;
			}
			return $ret;
		}

		public static function Filter(Subscriber $subscriber, $term='', $field='bakerysaleitemid')
		{
			$db = $subscriber->GetDB();
			$ret = array();
			$i = 0;

			$res = $db->query("SELECT * FROM bakerysaleitem WHERE ".$field." ='$term'");
			while(($row = $res->fetch_assoc()) != null)
			{
                $ret[$i] = new Bakerysaleitem($subscriber);
                $ret[$i]->Id = $row['bakerysaleitemid'];
                $ret[$i]->Created = new WixDate($row['created']);
                $ret[$i]->Item = $row['item'];
                $ret[$i]->Quantity = Convert::ToInt($row['quantity']);
				$i++;
			}
			return $ret;
		}

		public static function Order(Subscriber $subscriber, $field='id', $order='DESC')
		{
			$db = $subscriber->GetDB();
			$ret = array();
			$i = 0;

			$res = $db->query("SELECT * FROM bakerysaleitem ORDER BY ".$field." ".$order."");
			while(($row = $res->fetch_assoc()) != null)
			{
                $ret[$i] = new Bakerysaleitem($subscriber);
                $ret[$i]->Id = $row['bakerysaleitemid'];
                $ret[$i]->Created = new WixDate($row['created']);
                $ret[$i]->Item = $row['item'];
                $ret[$i]->Quantity = Convert::ToInt($row['quantity']);
				$i++;
			}
			return $ret;
		}

		public static function All(Subscriber $subscriber)
		{
			$db = $subscriber->GetDB();
			$ret = array();
			$i = 0;

			$res = $db->query("SELECT * FROM bakerysaleitem");
			while(($row = $res->fetch_assoc()) != null)
			{
				$ret[$i] = new Bakerysaleitem($subscriber);
				$ret[$i]->Id = $row['bakerysaleitemid'];
				$ret[$i]->Created = new WixDate($row['created']);
				$ret[$i]->Item = $row['item'];
				$ret[$i]->Quantity = Convert::ToInt($row['quantity']);
				$i++;
			}
			return $ret;
		}
	}
