<?php
	/* Generated by Wixnit Class Builder 
	// Jul, 06/2019
	// Building class for Country
	*/

	class Country
	{
		public $Id = "";
		public $Created = 0;
		public $Name = "";
		public $Code = "";
		public $Capital = "";
		public $Phonecode = "";
		public $Continent = "";
		public $Currency = "";

		public $Timezone = "";
		public $Region = "";
		public $Subregion = "";
		public $Code3 = "";
		public $Language = "";

		function __construct($arg=null)
		{
			if($arg != null)
			{
				$db = DB::GetDB();

				$res = $db->query("SELECT * FROM country WHERE countryid='$arg'");

				if($res->num_rows > 0)
				{
					$row = $res->fetch_assoc();
				
					$this->Id = $row['countryid'];
					$this->Created = new WixDate($row['created']);
					$this->Name = ucwords($row['name']);
					$this->Code = $row['code'];
					$this->Capital = ucwords($row['capital']);
					$this->Phonecode = $row['phonecode'];
					$this->Continent = $row['continent'];
					$this->Currency = $row['currency'];

                    $this->Timezone = $row['time_zone'];
                    $this->Region =  $row['region'];
                    $this->Subregion =  $row['subregion'];
                    $this->Code3 =  $row['code3'];
                    $this->Language =  $row['language'];
				}
			}
		}

		public function Save()
		{
			$db = DB::GetDB();

			$id = $this->Id;
			$created = time();
			$name = addslashes(strtolower($this->Name));
			$code = addslashes(strtolower($this->Code));
			$capital = addslashes(strtolower($this->Capital));
			$phonecode = addslashes(strtolower($this->Phonecode));
			$continent = addslashes(strtolower($this->Continent));
			$currency = addslashes(strtolower($this->Currency));

            $timezone = addslashes(strtolower($this->Timezone));
            $region = addslashes(strtolower($this->Region));
            $subregion = addslashes(strtolower($this->Subregion));
            $code3 = addslashes(strtolower($this->Code3));
            $language = addslashes(strtolower($this->Language));

			if($res = $db->query("SELECT countryid FROM country WHERE countryid='$id'")->num_rows > 0)
			{
				$db->query("UPDATE country SET name='$name',code='$code',capital='$capital',phonecode='$phonecode',continent='$continent',currency='$currency',time_zone='$timezone',language='$language',region='$region',subregion='$subregion',code3='$code3' WHERE countryid = '$id'");
			}
			else
			{
				redo: ;
				$id = Random::GenerateId(16);
				if($db->query("SELECT countryid FROM country WHERE countryid='$id'")->num_rows > 0)
				{
					goto redo;
				}
				$this->Id = $id;
				$db->query("INSERT INTO country(countryid,created,name,code,capital,phonecode,continent,currency,time_zone,language,region,subregion,code3) VALUES ('$id','$created','$name','$code','$capital','$phonecode','$continent','$currency','$timezone','$language','$region','$subregion','$code3')");
			}
		}

		public function Delete()
		{
			$db = DB::GetDB();

			$id = $this->Id;
			$db->query("DELETE FROM country WHERE countryid='$id'");

			//Deleting Associated Objects
			/*n			$this->Cities->Delete();
			*/
		}

		public static function Search($term='')
		{
			$db = DB::GetDB();
			$ret = array();
			$i = 0;

			$res = $db->query("SELECT * FROM country WHERE name LIKE '%$term%' OR code LIKE '%$term%' OR capital LIKE '%$term%' OR phonecode LIKE '%$term%' ORDER BY name ASC");
            while(($row = $res->fetch_assoc()) != null)
            {
                $ret[$i] = new Country();
                $ret[$i]->Id = $row['countryid'];
                $ret[$i]->Created = new WixDate($row['created']);
                $ret[$i]->Name = ucwords($row['name']);
                $ret[$i]->Code = $row['code'];
                $ret[$i]->Capital = $row['capital'];
                $ret[$i]->Phonecode = $row['phonecode'];
                $ret[$i]->Continent = $row['continent'];
                $ret[$i]->Currency = $row['currency'];

                $ret[$i]->Timezone = $row['time_zone'];
                $ret[$i]->Region =  $row['region'];
                $ret[$i]->Subregion =  $row['subregion'];
                $ret[$i]->Code3 =  $row['code3'];
                $ret[$i]->Language =  $row['language'];
                $i++;
            }
            $db->close();
            return $ret;
		}

		public static function Filter($term='', $field='countryid')
		{
			$db = DB::GetDB();
			$ret = array();
			$i = 0;

			$res = $db->query("SELECT * FROM country WHERE ".$field." ='$term'");
            while(($row = $res->fetch_assoc()) != null)
            {
                $ret[$i] = new Country();
                $ret[$i]->Id = $row['countryid'];
                $ret[$i]->Created = new WixDate($row['created']);
                $ret[$i]->Name = ucwords($row['name']);
                $ret[$i]->Code = $row['code'];
                $ret[$i]->Capital = $row['capital'];
                $ret[$i]->Phonecode = $row['phonecode'];
                $ret[$i]->Continent = $row['continent'];
                $ret[$i]->Currency = $row['currency'];

                $ret[$i]->Timezone = $row['time_zone'];
                $ret[$i]->Region =  $row['region'];
                $ret[$i]->Subregion =  $row['subregion'];
                $ret[$i]->Code3 =  $row['code3'];
                $ret[$i]->Language =  $row['language'];
                $i++;
            }
            $db->close();
            return $ret;
		}

		public static function Order($field='id', $order='DESC')
		{
			$db = DB::GetDB();
			$ret = array();
			$i = 0;

			$res = $db->query("SELECT * FROM country ORDER BY ".$field." ".$order."");
            while(($row = $res->fetch_assoc()) != null)
            {
                $ret[$i] = new Country();
                $ret[$i]->Id = $row['countryid'];
                $ret[$i]->Created = new WixDate($row['created']);
                $ret[$i]->Name = ucwords($row['name']);
                $ret[$i]->Code = $row['code'];
                $ret[$i]->Capital = $row['capital'];
                $ret[$i]->Phonecode = $row['phonecode'];
                $ret[$i]->Continent = $row['continent'];
                $ret[$i]->Currency = $row['currency'];

                $ret[$i]->Timezone = $row['time_zone'];
                $ret[$i]->Region =  $row['region'];
                $ret[$i]->Subregion =  $row['subregion'];
                $ret[$i]->Code3 =  $row['code3'];
                $ret[$i]->Language =  $row['language'];
                $i++;
            }
            $db->close();
            return $ret;
		}

		public static function GroupInitialize($array=null, $orderBy='id', $order='DESC')
		{
			$db = DB::GetDB();
			$ret = array();
			$i = 0;

			$query = "";

			if(is_array($array) === true)
			{
				if(count($array) == 0)
				{
					return $ret;
				}
				else
				{
					for($i = 0; $i < count($array); $i++)
					{
						if($query == "")
						{
							$query = " WHERE Countryid='".$array[$i]."'";
						}
						else
						{
							$query .= " OR Countryid ='".$array[$i]."'";
						}
					}
				}
			}
			$i = 0;
			$res = $db->query("SELECT * FROM country".$query." ORDER BY ".$orderBy." ".$order);
			while(($row = $res->fetch_assoc()) != null)
			{
				$ret[$i] = new Country();
				$ret[$i]->Id = $row['countryid'];
				$ret[$i]->Created = new WixDate($row['created']);
				$ret[$i]->Name = ucwords($row['name']);
				$ret[$i]->Code = $row['code'];
				$ret[$i]->Capital = $row['capital'];
				$ret[$i]->Phonecode = $row['phonecode'];
				$ret[$i]->Continent = $row['continent'];
				$ret[$i]->Currency = $row['currency'];

                $ret[$i]->Timezone = $row['time_zone'];
                $ret[$i]->Region =  $row['region'];
                $ret[$i]->Subregion =  $row['subregion'];
                $ret[$i]->Code3 =  $row['code3'];
                $ret[$i]->Language =  $row['language'];
				$i++;
			}
            $db->close();
			return $ret;
		}


		//Hand crafted methods

        public static function FromLocation(Location $location)
        {
            $code = $location->CountryCode;
            $ret = Country::ByCode($code);
            return $ret;
        }

        public static function ByCode($country_code)
        {
            $ret = new Country();
            $db = DB::GetDB();
            $res = $db->query("SELECT countryid FROM country WHERE code='$country_code'");

            if($res->num_rows > 0)
            {
                $row = $res->fetch_assoc();
                $ret = new Country($row['countryid']);
            }
            $db->close();
            return $ret;
        }
	}
