<?php
	/* Generated by Wixnit Class Builder 
	// Jan, 07/2020
	// Building class for Facilities
	*/

	class Facilities
	{
		public $Id = "";
		public $Created = 0;
		public $Icon = "";
		public $Heading = "";
		public $Body = "";
		public $Icontype = "";
		public $Sort = 0;
		public $Status = false;

		private $subscriber = null;

		function __construct(Subscriber $subscriber, $arg=null)
		{
			$this->subscriber = $subscriber;
		}

		public function Initialize($arg=null)
        {
            if($arg != null)
            {
                $db = $this->subscriber->GetDB();

                $res = $db->query("SELECT * FROM facilities WHERE facilitiesid='$arg'");

                if($res->num_rows > 0)
                {
                    $row = $res->fetch_assoc();

                    $this->Id = $row['facilitiesid'];
                    $this->Created = new WixDate($row['created']);
                    $this->Icon = $row['icon'];
                    $this->Heading = $row['heading'];
                    $this->Body = $row['body'];
                    $this->Icontype = $row['icontype'];
                    $this->Sort = $row['sort'];
                    $this->Status = Convert::ToBool($row['status']);
                }
            }
        }

		public function Save()
		{
			$db = $this->subscriber->GetDB();

			$id = $this->Id;
			$created = time();
			$icon = addslashes($this->Icon);
			$heading = addslashes($this->Heading);
			$body = addslashes($this->Body);
			$icontype = addslashes($this->Icontype);
			$sort = Convert::ToInt($this->Sort);
			$status = Convert::ToInt($this->Status);

			if($res = $db->query("SELECT facilitiesid FROM facilities WHERE facilitiesid='$id'")->num_rows > 0)
			{
				$db->query("UPDATE facilities SET icon='$icon',heading='$heading',body='$body',icontype='$icontype',sort='$sort',status='$status' WHERE facilitiesid = '$id'");
			}
			else
			{
				redo: ;
				$id = Random::GenerateId(16);
				if($db->query("SELECT facilitiesid FROM facilities WHERE facilitiesid='$id'")->num_rows > 0)
				{
					goto redo;
				}
				$this->Id = $id;
				$db->query("INSERT INTO facilities(facilitiesid,created,icon,heading,body,icontype,sort,status) VALUES ('$id','$created','$icon','$heading','$body','$icontype','$sort','$status')");
			}
		}

		public function Delete()
		{
			$db = $this->subscriber->GetDB();

			$id = $this->Id;
			$db->query("DELETE FROM facilities WHERE facilitiesid='$id'");
		}

		public static function Search(Subscriber $subscriber, $term='')
		{
			$db = $subscriber->GetDB();
			$ret = array();
			$i = 0;

			$res = $db->query("SELECT * FROM facilities WHERE icon LIKE '%$term%' OR heading LIKE '%$term%' OR body LIKE '%$term%' OR icontype LIKE '%$term%' OR sort LIKE '%$term%' OR status LIKE '%$term%'");
			while(($row = $res->fetch_assoc()) != null)
			{
                $ret[$i] = new Facilities($subscriber);
                $ret[$i]->Initialize($row['facilitiesid']);
                $ret[$i]->Id = $row['facilitiesid'];
                $ret[$i]->Created = new WixDate($row['created']);
                $ret[$i]->Icon = $row['icon'];
                $ret[$i]->Heading = $row['heading'];
                $ret[$i]->Body = $row['body'];
                $ret[$i]->Icontype = $row['icontype'];
                $ret[$i]->Sort = $row['sort'];
                $ret[$i]->Status = Convert::ToBool($row['status']);
                $i++;
			}
			return $ret;
		}

		public static function Filter(Subscriber $subscriber,$term='', $field='facilitiesid')
		{
			$db = $subscriber->GetDB();
			$ret = array();
			$i = 0;

			$res = $db->query("SELECT * FROM facilities WHERE ".$field." ='$term'");
			while(($row = $res->fetch_assoc()) != null)
			{
                $ret[$i] = new Facilities($subscriber);
                $ret[$i]->Initialize($row['facilitiesid']);
                $ret[$i]->Id = $row['facilitiesid'];
                $ret[$i]->Created = new WixDate($row['created']);
                $ret[$i]->Icon = $row['icon'];
                $ret[$i]->Heading = $row['heading'];
                $ret[$i]->Body = $row['body'];
                $ret[$i]->Icontype = $row['icontype'];
                $ret[$i]->Sort = $row['sort'];
                $ret[$i]->Status = Convert::ToBool($row['status']);
                $i++;
			}
			return $ret;
		}

		public static function Order(Subscriber $subscriber,$field='id', $order='DESC')
		{
			$db = $subscriber->GetDB();
			$ret = array();
			$i = 0;

			$res = $db->query("SELECT * FROM facilities ORDER BY ".$field." ".$order."");
			while(($row = $res->fetch_assoc()) != null)
			{
                $ret[$i] = new Facilities($subscriber);
                $ret[$i]->Initialize($row['facilitiesid']);
                $ret[$i]->Id = $row['facilitiesid'];
                $ret[$i]->Created = new WixDate($row['created']);
                $ret[$i]->Icon = $row['icon'];
                $ret[$i]->Heading = $row['heading'];
                $ret[$i]->Body = $row['body'];
                $ret[$i]->Icontype = $row['icontype'];
                $ret[$i]->Sort = $row['sort'];
                $ret[$i]->Status = Convert::ToBool($row['status']);
                $i++;
			}
			return $ret;
		}

		public static function All(Subscriber $subscriber)
		{
			$db = $subscriber->GetDB();
			$ret = array();
			$i = 0;

			$res = $db->query("SELECT * FROM facilities");
			while(($row = $res->fetch_assoc()) != null)
			{
				$ret[$i] = new Facilities($subscriber);
				$ret[$i]->Initialize($row['facilitiesid']);
				$ret[$i]->Id = $row['facilitiesid'];
				$ret[$i]->Created = new WixDate($row['created']);
				$ret[$i]->Icon = $row['icon'];
				$ret[$i]->Heading = $row['heading'];
				$ret[$i]->Body = $row['body'];
				$ret[$i]->Icontype = $row['icontype'];
				$ret[$i]->Sort = $row['sort'];
				$ret[$i]->Status = Convert::ToBool($row['status']);
				$i++;
			}
			return $ret;
		}
	}
