<?php
	/* Generated by Wixnit Class Builder 
	// Dec, 05/2019
	// Building class for Integration
	*/

	class Integration
	{
		public $Created = 0;
		public $Facebook = "";
		public $Twitter = "";
		public $Google = "";
		public $Whatsapp = "";
		public $Instagram = "";
		public $Telegram = "";
		public $Linkedin = "";
		public $Livechat = "";
		public $Analytics = "";
		public $Translator = "";
		public $Latitude = "";
		public $Longitude = "";
		public $Apikey = "";
		public $Googletag = "";

		private $subscriber  = null;

		function __construct(Subscriber $subscriber)
		{
			$db = $subscriber->GetDB();

			$this->subscriber = $subscriber;

			$res = $db->query("SELECT * FROM integration");

			if($res->num_rows > 0)
			{
				$row = $res->fetch_assoc();
			
				$this->Created = new WixDate($row['created']);
				$this->Facebook = $row['facebook'];
				$this->Twitter = $row['twitter'];
				$this->Google = $row['google'];
				$this->Whatsapp = $row['whatsapp'];
				$this->Instagram = $row['instagram'];
				$this->Telegram = $row['telegram'];
				$this->Linkedin = $row['linkedin'];
				$this->Livechat = $row['livechat'];
				$this->Analytics = $row['analytics'];
				$this->Translator = $row['translator'];
				$this->Latitude = $row['latitude'];
				$this->Longitude = $row['longitude'];
				$this->Apikey = $row['apikey'];
				$this->Googletag = $row['googletag'];
			}
			else
			{
				$this->Save();
			}
		}

		public function Save()
		{
			$db = $this->subscriber->GetDB();

			$created = time();
			$facebook = addslashes($this->Facebook);
			$twitter = addslashes($this->Twitter);
			$google = addslashes($this->Google);
			$whatsapp = addslashes($this->Whatsapp);
			$instagram = addslashes($this->Instagram);
			$telegram = addslashes($this->Telegram);
			$linkedin = addslashes($this->Linkedin);
			$livechat = addslashes($this->Livechat);
			$analytics = addslashes($this->Analytics);
			$translator = addslashes($this->Translator);
			$latitude = addslashes($this->Latitude);
			$longitude = addslashes($this->Longitude);
			$apikey = addslashes($this->Apikey);
			$googletag = addslashes($this->Googletag);

			if($res = $db->query("SELECT * FROM integration")->num_rows > 0)
			{
				$db->query("UPDATE integration SET facebook='$facebook',twitter='$twitter',google='$google',whatsapp='$whatsapp',instagram='$instagram',telegram='$telegram',linkedin='$linkedin',livechat='$livechat',analytics='$analytics',translator='$translator',latitude='$latitude',longitude='$longitude',apikey='$apikey',googletag='$googletag'");
			}
			else
			{
				$db->query("INSERT INTO integration(created,facebook,twitter,google,whatsapp,instagram,telegram,linkedin,livechat,analytics,translator,latitude,longitude,apikey,googletag) VALUES ('$created','$facebook','$twitter','$google','$whatsapp','$instagram','$telegram','$linkedin','$livechat','$analytics','$translator','$latitude','$longitude','$apikey','$googletag')");
			}
		}

		public function Delete()
		{
			$db = $this->subscriber->GetDB();

			$db->query("DELETE FROM integration");
		}

		public static function Order(Subscriber $subscriber, $field='id', $order='DESC')
		{
			$db = $subscriber->GetDB();
			$ret = array();
			$i = 0;

			$res = $db->query("SELECT integrationid FROM integration ORDER BY ".$field." ".$order."");
			while(($row = $res->fetch_assoc()) != null)
			{
				$ret[$i] = new Integration($row['integrationid']);
				$i++;
			}
			return $ret;
		}
	}
