<?php
	/* Generated by Wixnit Class Builder 
	// Feb, 16/2020
	// Building class for Quotationsession
	*/

	class Quotationsession
	{
		public $Id = "";
		public $Created = 0;
		public $Quotation = "";
		public $Supplier = "";
		public $Responded = false;
		public $Responsedate = "";
		public $Sms = false;
		public $Email = false;

		public $Type = "";

		private $subscriber = null;

		function __construct(Subscriber $subscriber)
		{
			$this->subscriber = $this->subscriber = $subscriber;
		}

		public function Initialize($arg=null)
        {
            if($arg != null)
            {
                $db = $this->subscriber->GetDB();

                $res = $db->query("SELECT * FROM quotationsession WHERE quotationsessionid='$arg'");

                if($res->num_rows > 0)
                {
                    $row = $res->fetch_assoc();

                    $this->Id = $row['quotationsessionid'];
                    $this->Created = new WixDate($row['created']);
                    $this->Quotation = $row['quotation'];
                    $this->Supplier = $row['supplier'];
                    $this->Responded = Convert::ToBool($row['responded']);
                    $this->Responsedate = $row['responsedate'];
                    $this->Sms = Convert::ToBool($row['sms']);
                    $this->Email = Convert::ToBool($row['email']);
                    $this->Type = $row['type'];
                }
            }
        }

		public function Save()
		{
			$db = $this->subscriber->GetDB();

			$id = $this->Id;
			$created = time();
			$quotation = addslashes($this->Quotation);
			$supplier = addslashes($this->Supplier);
			$responded = Convert::ToInt($this->Responded);
			$responsedate = addslashes($this->Responsedate);
			$sms = Convert::ToInt($this->Sms);
			$email = Convert::ToInt($this->Email);
			$type = addslashes($this->Type);

			if($res = $db->query("SELECT quotationsessionid FROM quotationsession WHERE quotationsessionid='$id'")->num_rows > 0)
			{
				$db->query("UPDATE quotationsession SET quotation='$quotation',supplier='$supplier',responded='$responded',responsedate='$responsedate',sms='$sms',email='$email',type='$type' WHERE quotationsessionid = '$id'");
			}
			else
			{
				redo: ;
				$id = Random::GenerateId(16);
				if($db->query("SELECT quotationsessionid FROM quotationsession WHERE quotationsessionid='$id'")->num_rows > 0)
				{
					goto redo;
				}
				$this->Id = $id;
				$db->query("INSERT INTO quotationsession(quotationsessionid,created,quotation,supplier,responded,responsedate,sms,email,type) VALUES ('$id','$created','$quotation','$supplier','$responded','$responsedate','$sms','$email','$type')");
			}
		}

		public function Delete()
		{
			$db = $this->subscriber->GetDB();

			$id = $this->Id;
			$db->query("DELETE FROM quotationsession WHERE quotationsessionid='$id'");
		}

		public static function Search(Subscriber $subscriber, $term='')
		{
			$db = $subscriber->GetDB();
			$ret = array();
			$i = 0;

			$res = $db->query("SELECT * FROM quotationsession WHERE quotation LIKE '%$term%' OR supplier LIKE '%$term%' OR responded LIKE '%$term%' OR responsedate LIKE '%$term%' OR sms LIKE '%$term%' OR email LIKE '%$term%'");
			while(($row = $res->fetch_assoc()) != null)
			{
                $ret[$i] = new Quotationsession($subscriber);
                $ret[$i]->Id = $row['quotationsessionid'];
                $ret[$i]->Created = new WixDate($row['created']);
                $ret[$i]->Quotation = $row['quotation'];
                $ret[$i]->Supplier = $row['supplier'];
                $ret[$i]->Responded = Convert::ToBool($row['responded']);
                $ret[$i]->Responsedate = $row['responsedate'];
                $ret[$i]->Sms = Convert::ToBool($row['sms']);
                $ret[$i]->Email = Convert::ToBool($row['email']);
                $ret[$i]->Type = $row['type'];
				$i++;
			}
			return $ret;
		}

		public static function Filter(Subscriber $subscriber, $term='', $field='quotationsessionid')
		{
			$db = $subscriber->GetDB();
			$ret = array();
			$i = 0;

			$res = $db->query("SELECT * FROM quotationsession WHERE ".$field." ='$term'");
			while(($row = $res->fetch_assoc()) != null)
			{
                $ret[$i] = new Quotationsession($subscriber);
                $ret[$i]->Id = $row['quotationsessionid'];
                $ret[$i]->Created = new WixDate($row['created']);
                $ret[$i]->Quotation = $row['quotation'];
                $ret[$i]->Supplier = $row['supplier'];
                $ret[$i]->Responded = Convert::ToBool($row['responded']);
                $ret[$i]->Responsedate = $row['responsedate'];
                $ret[$i]->Sms = Convert::ToBool($row['sms']);
                $ret[$i]->Email = Convert::ToBool($row['email']);
                $ret[$i]->Type = $row['type'];
				$i++;
			}
			return $ret;
		}

		public static function Order(Subscriber $subscriber, $field='id', $order='DESC')
		{
			$db = $subscriber->GetDB();
			$ret = array();
			$i = 0;

			$res = $db->query("SELECT * FROM quotationsession ORDER BY ".$field." ".$order."");
			while(($row = $res->fetch_assoc()) != null)
			{
                $ret[$i] = new Quotationsession($subscriber);
                $ret[$i]->Id = $row['quotationsessionid'];
                $ret[$i]->Created = new WixDate($row['created']);
                $ret[$i]->Quotation = $row['quotation'];
                $ret[$i]->Supplier = $row['supplier'];
                $ret[$i]->Responded = Convert::ToBool($row['responded']);
                $ret[$i]->Responsedate = $row['responsedate'];
                $ret[$i]->Sms = Convert::ToBool($row['sms']);
                $ret[$i]->Email = Convert::ToBool($row['email']);
                $ret[$i]->Type = $row['type'];
				$i++;
			}
			return $ret;
		}

		public static function All(Subscriber $subscriber)
		{
			$db = $subscriber->GetDB();
			$ret = array();
			$i = 0;

			$res = $db->query("SELECT * FROM quotationsession");
			while(($row = $res->fetch_assoc()) != null)
			{
				$ret[$i] = new Quotationsession($subscriber);
				$ret[$i]->Id = $row['quotationsessionid'];
				$ret[$i]->Created = new WixDate($row['created']);
				$ret[$i]->Quotation = $row['quotation'];
				$ret[$i]->Supplier = $row['supplier'];
				$ret[$i]->Responded = Convert::ToBool($row['responded']);
				$ret[$i]->Responsedate = $row['responsedate'];
				$ret[$i]->Sms = Convert::ToBool($row['sms']);
				$ret[$i]->Email = Convert::ToBool($row['email']);
                $ret[$i]->Type = $row['type'];
				$i++;
			}
			return $ret;
		}

		public static function GetSession(Subscriber $subscriber, $quotation, $supplier)
        {
            $db = $subscriber->GetDB();
            $ret = null;

            $res = $db->query("SELECT * FROM quotationsession WHERE quotation='$quotation' AND supplier='$supplier'");
            while(($row = $res->fetch_assoc()) != null)
            {
                $ret = new Quotationsession($subscriber);
                $ret->Id = $row['quotationsessionid'];
                $ret->Created = new WixDate($row['created']);
                $ret->Quotation = $row['quotation'];
                $ret->Supplier = $row['supplier'];
                $ret->Responded = Convert::ToBool($row['responded']);
                $ret->Responsedate = $row['responsedate'];
                $ret->Sms = Convert::ToBool($row['sms']);
                $ret->Email = Convert::ToBool($row['email']);
                $ret->Type = $row['type'];
            }
            return $ret;
        }
	}
